### ISSUE TITLE
libmpv Audio/Video desynchronisation detected & playlist loading error

### ISSUE THREAD

**Issue by skaox** [yuki-iptv/yuki-iptv#10]
Hi,

info/log when yuki-iptv start :

```
yuki-iptv INFO: Qt init...
yuki-iptv INFO: Qt init successful
yuki-iptv INFO: 
yuki-iptv INFO: app.setStyle("fusion") OK
yuki-iptv INFO: 
yuki-iptv INFO: yuki-iptv starting...
yuki-iptv INFO: Copyright (c) 2021, 2022 Astroncia
yuki-iptv INFO: Copyright (c) 2023 yuki-chan-nya
yuki-iptv INFO: 
yuki-iptv INFO: This program is free software: you can redistribute it and/or modify
yuki-iptv INFO: it under the terms of the GNU General Public License as published by
yuki-iptv INFO: the Free Software Foundation, either version 3 of the License, or
yuki-iptv INFO: (at your option) any later version.
yuki-iptv INFO: 
yuki-iptv INFO: The Font Awesome pictograms are licensed under the CC BY 4.0 License.
yuki-iptv INFO: https://fontawesome.com/
yuki-iptv INFO: https://creativecommons.org/licenses/by/4.0/
yuki-iptv INFO: 
yuki-iptv INFO: yuki-iptv version: 0.0.5
yuki-iptv INFO: Using Python 3.8.10 (default, Mar 13 2023, 10:26:41) [GCC 9.4.0]
yuki-iptv INFO: Qt library: PyQt5
yuki-iptv INFO: Qt version: 5.15.2
yuki-iptv INFO: 
yuki-iptv INFO: Hardware acceleration enabled
yuki-iptv INFO: Catchup disabled
yuki-iptv INFO: Init m3u editor
yuki-iptv INFO: M3u editor init done
yuki-iptv INFO: Playlist caching off
yuki-iptv INFO: Loading playlist...
yuki-iptv INFO: Status code: 200
yuki-iptv INFO: 558429 bytes
yuki-iptv INFO: XXXX channels, XX groups, 0 movies, 0 series
yuki-iptv INFO: Playling loading done!
yuki-iptv INFO: Default user agent: Mozilla/5.0
yuki-iptv INFO: Default HTTP referer: (empty)
yuki-iptv INFO: Always on top disabled
yuki-iptv INFO: Testing custom mpv options...
yuki-iptv INFO: {}
yuki-iptv INFO: mpv options OK
yuki-iptv INFO: Using mpv options: {"vo": "gpu,x11", "hwdec": "auto-safe", "cursor-autohide": 1000, "force-window": true}
yuki-iptv INFO: catchup-days = 1
yuki-iptv INFO: No hotkeys.json found, using default hotkeys
yuki-iptv INFO: Using mpv 0.34.0-98-g77142ed9b8
yuki-iptv INFO: Demuxer cache set to 3s
yuki-iptv INFO: Cache set to 3s
yuki-iptv INFO: No HTTP referer set up
yuki-iptv INFO: Starting MPRIS loop
yuki-iptv INFO: Set volume to 77
yuki-iptv INFO: Restoring main window position...
yuki-iptv INFO: Main window position restored
yuki-iptv INFO: Show splash
yuki-iptv INFO: Reading cached TV guide...
libmpv INFO: [info] cplayer:  (+) Video --vid=1 (png 800x600 1.000fps)
libmpv INFO: [info] cplayer: VO: [gpu] 800x600 rgb24
yuki-iptv INFO: Connection loss detector disabled
yuki-iptv INFO: TV guide read done, took 1.33 seconds
```

when Audio/Video desynchronisation is detected sound continue but video is frozen then come back a few seconds later :

```
libmpv INFO: [warn] cplayer: Audio device underrun detected.
yuki-iptv INFO: Disabling deinterlace for main.png
libmpv INFO: [info] cplayer:  (+) Video --vid=1 (png 800x600 1.000fps)
libmpv INFO: [info] cplayer: VO: [gpu] 800x600 rgb24
libmpv INFO: [warn] cplayer: Audio device underrun detected.
libmpv INFO: [warn] cplayer: Audio device underrun detected.
libmpv INFO: [warn] cplayer: Audio/Video desynchronisation detected! Possible reasons include too slow
libmpv INFO: [warn] cplayer: hardware, temporary CPU spikes, broken drivers, and broken files. Audio
libmpv INFO: [warn] cplayer: position will not match to the video (see A-V status field).
libmpv INFO: [warn] cplayer: Audio device underrun detected.
```

Sometimes playlist can't be loaded  :

```
yuki-iptv INFO: Loading playlist...
yuki-iptv WARNING: Playlist load failed, trying empty user agent
yuki-iptv WARNING: Playlist URL loading error!
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 426, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 421, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/lib/python3.8/http/client.py", line 1348, in getresponse
    response.begin()
  File "/usr/lib/python3.8/http/client.py", line 316, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.8/http/client.py", line 277, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/lib/python3.8/socket.py", line 669, in readinto
    return self._sock.recv_into(b)
socket.timeout: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 726, in urlopen
    retries = retries.increment(
  File "/usr/lib/python3/dist-packages/urllib3/util/retry.py", line 410, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/usr/lib/python3/dist-packages/six.py", line 703, in reraise
    raise value
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 670, in urlopen
    httplib_response = self._make_request(
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 428, in _make_request
    self._raise_timeout(err=e, url=url, timeout_value=read_timeout)
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 335, in _raise_timeout
    raise ReadTimeoutError(
urllib3.exceptions.ReadTimeoutError: HTTPConnectionPool(host='domain.abc', port=80): Read timed out. (read timeout=3)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./yuki-iptv.py", line 887, in <module>
    m3u_req = requests.get(
  File "/usr/lib/python3/dist-packages/requests/api.py", line 76, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 529, in send
    raise ReadTimeout(e, request=request)
requests.exceptions.ReadTimeout: HTTPConnectionPool(host='domain.abc', port=80): Read timed out. (read timeout=3)
```

I'm using a fork of hypnotix (tvdemon) who's also using libmpv and have nothing to report with it same provider, channels, ...

Thank you in advance

**Comment by skaox** [comment]
Sorry for the delay and thank you mpv option work.

After reading [mpv wiki VIDEO OUTPUT DRIVERS](https://github.com/mpv-player/mpv/blob/master/DOCS/man/vo.rst)
and trying more combinations those 3 are working
```
vo=x11
vo=x11 hwdec=auto-safe
vo=x11 hwdec=vdpau (using this one)
```

Now there's a completely random cut of the stream just before cache is going down 4 3 2 1 0 and stop
```
libmpv INFO: [info] cplayer: 
libmpv INFO: [info] cplayer:  (+) Video --vid=1 (png 800x600 1.000fps)
libmpv INFO: [info] cplayer: VO: [x11] 800x600 rgb24
```

Very rarely with an invalid audio sync before
```
libmpv INFO: [warn] ad: Invalid audio PTS: 10.005333 -> 0.005333
libmpv INFO: [warn] cplayer: Reset playback due to audio timestamp reset.
libmpv INFO: [info] cplayer: 
yuki-iptv INFO: Disabling deinterlace for main.png
libmpv INFO: [info] cplayer: 
libmpv INFO: [info] cplayer:  (+) Video --vid=1 (png 800x600 1.000fps)
libmpv INFO: [info] cplayer: VO: [x11] 800x600 rgb24
```

Same invalid audio sync here without a cut/stop just a quick replay then continue like nothing happen
```
libmpv INFO: [warn] ad: Invalid audio PTS: 14.613333 -> 0.005333
libmpv INFO: [warn] cplayer: Reset playback due to audio timestamp reset.
libmpv INFO: [warn] ad: Invalid audio PTS: 7.685333 -> 0.010656
libmpv INFO: [warn] cplayer: Reset playback due to audio timestamp reset.
```

Settings -> Network -> Cache : 10
Most of the time only 5s or less.

Channel -> right clic -> select
sometimes nothing happen in GUI but in terminal
```
Traceback (most recent call last):
  File "./yuki-iptv.py", line 5465, in select_context_menu
    itemClicked_event(sel_item)
  File "./yuki-iptv.py", line 4467, in itemClicked_event
    if len(channel_name) > MAX_CHAN_SIZE:
TypeError: object of type 'QListWidgetItem' has no len()
Traceback (most recent call last):
  File "./yuki-iptv.py", line 5329, in redraw_chans
    channels_1 = gen_chans()
  File "./yuki-iptv.py", line 5283, in gen_chans
    j1 = playing_chan.lower()
AttributeError: 'QListWidgetItem' object has no attribute 'lower'
```

[9a45ecf](https://github.com/yuki-iptv/yuki-iptv/commit/9a45ecf6afc814e6f10a2f3bcd509a4500eb95f8) replaced usr/lib/yuki-iptv/yuki-iptv.py but doesn't start a window Error appear and if validation OK -> Game Over
```
yuki-iptv error

Traceback (most recent call last):
  File "./yuki-iptv.py", line 3089, in <module>
    hideepgfromplaylist_flag.setChecked(settings["hideepgfromplaylist"])
KeyError: 'hideepgfromplaylist'
```

Terminal :
```
yuki-iptv INFO: Default user agent: Mozilla/5.0
yuki-iptv INFO: Default HTTP referer: (empty)
yuki-iptv WARNING: ERROR
yuki-iptv WARNING: 
yuki-iptv WARNING: Traceback (most recent call last):
  File "./yuki-iptv.py", line 3089, in <module>
    hideepgfromplaylist_flag.setChecked(settings["hideepgfromplaylist"])
KeyError: 'hideepgfromplaylist'
```

First time I tried modified yuki-iptv.py
Settings -> GUI -> Hide the current television program
was activated but same thing even if unchecked.

Increase connect and read timeout work playlist is loaded every time before error appear.

**Comment by skaox** [comment]
It's working ! Perfect a big THANK YOU

**Comment by skaox** [comment]
> > Now there's a completely random cut of the stream just before cache is going down 4 3 2 1 0 and stop
> > Very rarely with an invalid audio sync before
> > Same invalid audio sync here without a cut/stop just a quick replay then continue like nothing happen
> 
> Do you have multicast (**udp://** or **rtp://**) links in your playlist?

No
