### ISSUE TITLE
Issues with special character in playlists in M3U format

### ISSUE THREAD

**Issue by LITUATUI** [yuki-iptv/yuki-iptv#12]
Hi.

I have a M3U playlist that shows wrong character on channel names when special character (´) is used.

For example:

- SIC Notícias shows as SIC Not√≠cias
- Canal História shows as Canal Hist√≥ria

![Yuki-IPTV-wrong-character](https://github.com/yuki-iptv/yuki-iptv/assets/49299328/c1c23bf1-e124-4530-9098-105693d98b27)

However, I have another smaller M3U playlist that shows this special character without problems. Both lists were made by me.

This only happens with channel names, EPG is always fine, even when the special character is present.

Is Yuki-IPTV having trouble to detect the charset (UTF-8) and that's why the channel names don't appear correctly?

**Comment by LITUATUI** [comment]
18:38:56.688 yuki-iptv INFO: Qt init...
18:38:56.806 yuki-iptv INFO: Qt init successful
18:38:56.806 yuki-iptv INFO: 
18:38:56.814 yuki-iptv INFO: app.setStyle("fusion") OK
18:38:56.814 yuki-iptv INFO: 
18:38:56.814 yuki-iptv INFO: yuki-iptv starting...
18:38:56.814 yuki-iptv INFO: Copyright (c) 2021, 2022 Astroncia
18:38:56.814 yuki-iptv INFO: Copyright (c) 2023 yuki-chan-nya
18:38:56.814 yuki-iptv INFO: 
18:38:56.814 yuki-iptv INFO: This program is free software: you can redistribute it and/or modify
18:38:56.814 yuki-iptv INFO: it under the terms of the GNU General Public License as published by
18:38:56.814 yuki-iptv INFO: the Free Software Foundation, either version 3 of the License, or
18:38:56.815 yuki-iptv INFO: (at your option) any later version.
18:38:56.815 yuki-iptv INFO: 
18:38:56.815 yuki-iptv INFO: The Font Awesome pictograms are licensed under the CC BY 4.0 License.
18:38:56.815 yuki-iptv INFO: https://fontawesome.com/
18:38:56.815 yuki-iptv INFO: https://creativecommons.org/licenses/by/4.0/
18:38:56.815 yuki-iptv INFO: 
18:38:56.815 yuki-iptv INFO: yuki-iptv version: 0.0.6
18:38:56.815 yuki-iptv INFO: Using Python 3.11.3 (main, Apr  5 2023, 15:52:25) [GCC 12.2.1 20230201]
18:38:56.815 yuki-iptv INFO: Qt library: PyQt6
18:38:56.815 yuki-iptv INFO: Qt version: 6.5.0
18:38:56.815 yuki-iptv INFO: 
18:38:56.916 yuki-iptv INFO: Hardware acceleration enabled
18:38:56.922 yuki-iptv INFO: Detected dark window theme, applying icons compat
18:38:56.923 yuki-iptv INFO: Catchup disabled
18:38:56.935 yuki-iptv INFO: Init m3u editor
18:38:56.977 yuki-iptv INFO: M3u editor init done
18:38:56.977 yuki-iptv INFO: Playlist caching off
18:38:56.978 yuki-iptv INFO: Loading playlist...
18:38:58.516 yuki-iptv INFO: Status code: 200
18:38:58.517 yuki-iptv INFO: 190240 bytes
18:38:59.489 yuki-iptv INFO: 750 channels, 17 groups, 0 movies, 0 series
18:38:59.490 yuki-iptv INFO: Playling loading done!
18:38:59.534 yuki-iptv INFO: Default user agent: Mozilla/5.0
18:38:59.535 yuki-iptv INFO: Default HTTP referer: (empty)
18:38:59.577 yuki-iptv INFO: Always on top disabled
18:38:59.751 yuki-iptv INFO: Testing custom mpv options...
18:38:59.751 yuki-iptv INFO: {}
18:38:59.759 yuki-iptv INFO: mpv options OK
18:38:59.759 yuki-iptv INFO: Using mpv options: {"vo": "gpu,x11", "hwdec": "auto-safe", "cursor-autohide": 1000, "force-window": true}
18:38:59.861 yuki-iptv INFO: catchup-days = 1
18:38:59.863 yuki-iptv INFO: No hotkeys.json found, using default hotkeys
18:38:59.906 yuki-iptv INFO: Using mpv 0.35.1-dirty
18:38:59.907 yuki-iptv INFO: Demuxer cache set to 20s
18:38:59.908 yuki-iptv INFO: Cache set to 20s
18:38:59.908 yuki-iptv INFO: No HTTP referer set up
18:38:59.962 yuki-iptv INFO: Starting MPRIS loop
18:39:00.054 yuki-iptv INFO: Set volume to 98
18:39:00.072 yuki-iptv INFO: 
18:39:00.072 yuki-iptv INFO: Playing 'SIC Not√≠cias' ('https://sicnot.live.impresa.pt/sicnot.m3u8')
18:39:00.082 yuki-iptv INFO: Using User-Agent: Mozilla/5.0
18:39:00.083 yuki-iptv INFO: Using HTTP Referer: (empty)
18:39:00.083 yuki_iptv.catchup INFO: 
18:39:00.083 yuki_iptv.catchup INFO: orig spec url: https://sicnot.live.impresa.pt/sicnot.m3u8
18:39:00.084 yuki_iptv.catchup INFO: after spec url: https://sicnot.live.impresa.pt/sicnot.m3u8
18:39:00.084 yuki_iptv.catchup INFO: 
18:39:00.087 yuki-iptv INFO: setPlayerSettings waiting for channel load...
18:39:00.246 yuki-iptv INFO: Playing last channel, splash turned off
18:39:00.247 yuki-iptv INFO: Reading cached TV guide...
18:39:00.424 yuki-iptv INFO: Connection loss detector enabled
/usr/lib/python3.11/site-packages/gi/overrides/GLib.py:123: Warning: g_variant_builder_end: assertion 'GVSB(builder)->offset >= GVSB(builder)->min_items' failed
  return builder.end()
18:39:00.511 pydbus.registration ERROR: Exception while handling org.freedesktop.DBus.Properties.GetAll()
Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/pydbus/registration.py", line 81, in call_method
    result = method(*parameters, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/pydbus/registration.py", line 110, in GetAll
    ret[local] = GLib.Variant(type, getattr(self.object, local))
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/gi/overrides/GLib.py", line 190, in __new__
    v.format_string = format_string
    ^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'format_string'
18:39:01.066 yuki-iptv INFO: TV guide read done, took 0.82 seconds
qt.gui.imageio: libpng warning: iCCP: known incorrect sRGB profile
18:39:03.817 libmpv INFO: [warn] demux: Not seekable, but enabling seeking on user request.
18:39:03.818 libmpv INFO: [info] cplayer:  (+) Video --vid=1 (h264 1920x1080 25.000fps)
18:39:03.818 libmpv INFO: [info] cplayer:  (+) Audio --aid=1 (aac 2ch 48000Hz)
Cannot load libcuda.so.1
18:39:03.884 libmpv INFO: [info] vd: Using hardware decoding (vaapi).
18:39:03.890 libmpv INFO: [info] cplayer: AO: [pipewire] 48000Hz stereo 2ch floatp
18:39:03.892 libmpv INFO: [info] cplayer: VO: [gpu] 1920x1080 vaapi[nv12]
18:39:03.898 yuki_iptv.menubar INFO: YukiData.first_run
18:39:03.900 yuki-iptv INFO: setPlayerSettings 'SIC Not√≠cias'
18:39:03.942 yuki-iptv INFO: Deinterlace: enabled
18:39:03.942 yuki-iptv INFO: Contrast: 0
18:39:03.942 yuki-iptv INFO: Brightness: 0
18:39:03.942 yuki-iptv INFO: Hue: 0
18:39:03.942 yuki-iptv INFO: Saturation: 0
18:39:03.942 yuki-iptv INFO: Gamma: 0
18:39:03.942 yuki-iptv INFO: Video aspect: -1.0
18:39:03.942 yuki-iptv INFO: Zoom: 0.0
18:39:03.942 yuki-iptv INFO: Panscan: 0.0
qt.gui.imageio: libpng warning: iCCP: known incorrect sRGB profile
^C18:39:19.417 yuki-iptv INFO: Saving active vf filters...
18:39:19.426 yuki-iptv INFO: Active vf filters saved
18:39:19.426 yuki-iptv INFO: Saving main window position / width / height...
18:39:19.427 yuki-iptv INFO: Main window position / width / height saved
18:39:19.428 libmpv INFO: [warn] vo/gpu/x11: Our window was destroyed, exiting
18:39:19.428 libmpv INFO: [warn] vo/gpu/x11: Our window was destroyed, exiting
18:39:19.441 yuki-iptv INFO: Stopped
18:39:19.468 libmpv INFO: [error] vo/gpu/x11: X11 error: BadWindow (invalid Window parameter)
18:39:19.468 libmpv INFO: [error] vo/gpu/x11: Type: 0, display: 0x7f96f4002880, resourceid: 5c00002, serial: 211
18:39:19.468 libmpv INFO: [error] vo/gpu/x11: Error code: 3, request code: 94, minor code: 1
18:39:19.500 libmpv INFO: [error] vo/gpu/x11: X11 error: BadWindow (invalid Window parameter)
18:39:19.501 libmpv INFO: [error] vo/gpu/x11: Type: 0, display: 0x7f96f4002880, resourceid: 5c00002, serial: 212
18:39:19.501 libmpv INFO: [error] vo/gpu/x11: Error code: 3, request code: 94, minor code: 1

**Comment by LITUATUI** [comment]
Just tried the new file and it works great, thanks!
