### ISSUE TITLE
Exception: Malformed M3U

### ISSUE THREAD

**Issue by faveoled** [yuki-iptv/yuki-iptv#18]
```
Traceback (most recent call last):
  File "/usr/lib/yuki-iptv/./yuki-iptv.py", line 944, in <module>
    m3u_data0 = m3u_parser.parse_m3u(m3u)
                ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/yuki-iptv/yuki_iptv/m3u.py", line 171, in parse_m3u
    raise Exception("Malformed M3U")
```

https://iptv-org.github.io/iptv/index.m3u

**Comment by faveoled** [comment]
I don't know, went for another app

**Comment by gromez** [comment]
Just tried with the same URL, no problem with M3U parsing.
