### ISSUE TITLE
TypeError: can only concatenate str (not "NoneType") to str

### ISSUE THREAD

**Issue by faveoled** [yuki-iptv/yuki-iptv#55]
```
Traceback (most recent call last):
  File "/usr/lib/yuki-iptv/./yuki-iptv.py", line 5865, in redraw_chans
    channels_1 = gen_chans()
  File "/usr/lib/yuki-iptv/./yuki-iptv.py", line 5653, in gen_chans
    prog = str(percentage) + "% " + current_prog["title"]
TypeError: can only concatenate str (not "NoneType") to str
```
deb 0.0.9, happened with this list:
https://github.com/luongz/iptv-jp

**Comment by faveoled** [comment]
> (Run `rm -v ~/.config/yuki-iptv/epg.cache` to remove broken EPG cache)

Can it be done by the software itself?
